= rustc_codegen_gcc: Progress Report #8
:page-navtitle: rustc_codegen_gcc: Progress Report #8
:page-liquid:

== What is rustc_codegen_gcc?

https://github.com/rust-lang/rustc_codegen_gcc[rustc_codegen_gcc] is a
GCC codegen for rustc, meaning that it can be loaded by the existing
rustc frontend, but benefits from GCC by having more architectures
supported and having access to GCC's optimizations.

== GCC patches status

This month, I submitted a few patches to GCC. None of them were merged
yet, but some of them got a review:

 * https://gcc.gnu.org/pipermail/jit/2022q1/001465.html[libgccjit: Add support for bitcasts [PR104071\]]
 * https://gcc.gnu.org/pipermail/jit/2022q1/001466.html[libgccjit: Add support for register variables [PR104072\]]
 * https://gcc.gnu.org/pipermail/jit/2022q1/001469.html[libgccjit: Add option to hide stderr logs [PR104073\]] (approved)
 * https://gcc.gnu.org/pipermail/jit/2022q1/001494.html[libgccjit: Add support for setting the alignment [PR104293\]]

== State of rustc_codegen_gcc

Here's what has been done this month:

 * https://github.com/rust-lang/rustc_codegen_gcc/pull/103[Support 128-bit integers on platforms without native support] (it doesn't handle endianness correctly yet, but I wanted to merge it and will fix this later)
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/115[Correctly import foreign statics] (thanks to bjorn3!)
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/118[Support -Zfunction-sections] (thanks to bjorn3!)
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/121[Support upgrading the alignment of a global variable]
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/125[Implement simd_neg]

Here are the results of running the UI tests in the https://github.com/rust-lang/rustc_codegen_gcc/runs/5014647023?check_suite_focus=true#step:17:9087[CI]:

[script,bash]
----
test result: FAILED. 4448 passed; 75 failed; 55 ignored; 0 measured; 0 filtered out; finished in 602.41s
----

https://github.com/rust-lang/rustc_codegen_gcc/runs/5014647064?check_suite_focus=true#step:17:9077[The
CI workflow testing without native 128-bit integers shows the same results.]

For the next month, now that the huge task of supporting 128-bit
integers on platforms without native support is done, I'll start
working either on supporting SIMD or unwinding.
Both of those features will take time and require writing a
non-trivial libgccjit patch.

== How to contribute

=== `rustc_codegen_gcc`

If you want to help on the project itself, please do the following:

 1. Run the tests locally.
 2. Choose a test that fails.
 3. Investigate why it fails.
 4. Fix the problem.

Even if you can't fix the problem, your investigation could help, so
if you enjoy staring at assembly code, have fun!

=== Crates and rustc

If you would like to contribute on adding support for Rust on
currently unsupported platforms, you can help by adding the support
for those platforms in some crates like `libc` and `object` and also
in the rust compiler itself.

=== Test this project

Otherwise, you can test this project on new platforms and also compare
the assembly with LLVM to see if some optimization is missing.

=== Good first issue

Finally, another good way to help is to look at https://github.com/rust-lang/rustc_codegen_gcc/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[good first issues]. Those are issues that should be easier to start with.

== Thanks for your support!

I wanted to personally thank all the people that sponsor this project:
your support is very much appreciated.

A special thanks to the following sponsors:

 * igrr
 * saethlin
 * embark-studios
 * Traverse-Research
 * Thomas Colliers
 * Shnatsel

A big thank you to bjorn3 for his help, contributions and reviews.
And a big thank you to lqd and https://github.com/GuillaumeGomez[GuillaumeGomez] for answering my
questions about rustc's internals.
Another big thank you to Commeownist for his contributions.

Also, a big thank you to the rest of my sponsors:

 * kpp
 * repi
 * nevi-me
 * Alovchin91
 * oleid
 * acshi
 * joshtriplett
 * djc
 * TimNN
 * sdroege
 * pcn
 * steven-joruk
 * davidlattimore
 * Nehliin
 * colelawrence
 * zmanian
 * alexkirsz
 * regiontog
 * berkus
 * wezm
 * belzael
 * vincentdephily
 * mexus
 * jam1garner
 * Shoeboxam
 * evanrichter
 * stuhood
 * yerke
 * bes
 * raymanfx
 * seanpianka
 * srijs
 * 0xdeafbeef
 * kkysen
 * messense
 * riking
 * rafaelcaricio
 * Lemmih
 * memoryruins
 * pthariensflame
 * senden9
 * Hofer-Julian
 * robjtede
 * Jonas Platte
 * spike grobstein
 * Oliver Marshall
 * Sam Harrington
 * Jonas
 * Jeff Muizelaar
 * Chris Butler
 * sierrafiveseven
 * Joseph Garvin
 * icewind
 * Sebastian Zivota
 * Oskar Nehlin
 * Nicolas Barbier
 * Daniel
 * Justin Ossevoort
 * sstadick
 * luizirber
 * kiyoshigawa
 * robinmoussu

and a few others who preferred to stay anonymous.
