= rustc_codegen_gcc: Progress Report #12
:page-navtitle: rustc_codegen_gcc: Progress Report #12
:page-liquid:

== What is rustc_codegen_gcc?

https://github.com/rust-lang/rustc_codegen_gcc[rustc_codegen_gcc] is a
GCC https://en.wikipedia.org/wiki/Ahead-of-time_compilation[ahead-of-time] codegen for rustc, meaning that it
can be loaded by the existing rustc frontend, but benefits from GCC by having more architectures
supported and having access to GCC's optimizations.
It is not to be confused with gccrs, which is a GCC frontend for Rust.

== GCC patches status

Again this month, there was a lot of progress!
The following patches were posted to the mailing list:

 * https://gcc.gnu.org/pipermail/jit/2022q2/001546.html[libgccjit: Fix bug where unary_op will return an integer type instead of the correct type]
 * https://gcc.gnu.org/pipermail/jit/2022q2/001548.html[libgccjit: Fix infinite recursion in gt_ggc_mx_lang_tree_node]
 * https://gcc.gnu.org/pipermail/jit/2022q2/001551.html[libgccjit: Support getting the size of a float]

The last patch was already approved and is https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=5940b4e59f8e198dbf7e8b733561ef72a9ba2cbc[merged].

I still have a few that I need to prepare and send for review and I'll send them on the GCC mailing list this month.

== State of rustc_codegen_gcc

Here's what has been done this month:

 * https://github.com/rust-lang/rustc_codegen_gcc/pull/175[Auto-generate even more mappings between GCC and LLVM builtins]
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/179[Sync from Rust]
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/176[Even more SIMD intrinsics]

The work on SIMD is still not completed as I cannot compile stdarch yet, but there's been good progress.
I believe I'm close to getting it to compile as I currently need to debug an RTL issue, so hopefully next month it will
compile.

Here's a rough summary of what has been implemented:

[cols="<,<,1,1"]
|===
| Feature | Last month completion | Completion | Delta

| target-specific builtins support in libgccjit
| Done
|
|

| support for vector shuffle (equivalent of `__builtin_shufflevector`) in libgccjit
| Done
|
|

| `simd_extract`
| Done
|
|

| `simd_select`, `simd_select_bitmask`
| Done
|
|

| `simd_reduce_min`, `simd_reduce_max`
| Done
|
|

| `simd_reduce_and`, `simd_reduce_or`
| Done
|
|

| `simd_saturating_add` and `simd_saturating_sub`
| implemented for x86
|
|

| `simd_insert`
| 20% implemented
| 100%
| +80%

| `simd_cast`
| 20% implemented
| 100%
| +80%

| `simd_bitmask`
| 0%
| 100%
| +100%

| LLVM SIMD intrinsics
| ~70% implemented for x86
| ~90% implemented for x86
| +20%

| `simd_reduce_add_unordered`, `simd_reduce_mul_unordered`
| 50%
| 50%
| 0

| `simd_reduce_add_ordered`, `simd_reduce_mul_ordered`
| 0%
| 0%
| 0

| `simd_reduce_min_nanless`, `simd_reduce_max_nanless`
| 0%
| 0%
| 0

| `simd_reduce_xor`, `simd_reduce_all`, `simd_reduce_any`
| 0%
| 0%
| 0

| SIMD float intrinsics
| 0%
| 0%
| 0

| `simd_gather` and `simd_scatter`
| 0%
| 0%
| 0

| `simd_as`
| 0%
| 0%
| 0
|===

=== UI tests progress

Here are the results of running the UI tests in the https://github.com/rust-lang/rustc_codegen_gcc/runs/6823429885?check_suite_focus=true#step:18:10160[CI]:

|===
| Category | Last Month | This Month | Delta

| Passed | 4598 | 4697 | +99
| Failed | 64 | 61 | -3
|===

For the next month, I'll continue working on SIMD support.

== How to contribute

=== `rustc_codegen_gcc`

If you want to help on the project itself, please do the following:

 1. Run the tests locally.
 2. Choose a test that fails.
 3. Investigate why it fails.
 4. Fix the problem.

Even if you can't fix the problem, your investigation could help, so
if you enjoy staring at assembly code, have fun!

=== Crates and rustc

If you would like to contribute on adding support for Rust on
currently unsupported platforms, you can help by adding the support
for those platforms in some crates like `libc` and `object` and also
in the rust compiler itself.

=== Test this project

Otherwise, you can test this project on new platforms and also compare
the assembly with LLVM to see if some optimization is missing.

=== Good first issue

Finally, another good way to help is to look at https://github.com/rust-lang/rustc_codegen_gcc/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[good first issues]. Those are issues that should be easier to start with.

== Thanks for your support!

I wanted to personally thank all the people that sponsor this project:
your support is very much appreciated.

A special thanks to the following sponsors:

 * saethlin
 * embark-studios
 * Traverse-Research
 * Shnatsel

A big thank you to bjorn3 for his help, contributions and reviews.
And a big thank you to lqd and https://github.com/GuillaumeGomez[GuillaumeGomez] for answering my
questions about rustc's internals.
Another big thank you to Commeownist for his contributions.

Also, a big thank you to the rest of my sponsors:

 * kpp
 * 0x7CFE
 * repi
 * nevi-me
 * oleid
 * acshi
 * joshtriplett
 * djc
 * TimNN
 * sdroege
 * pcn
 * alanfalloon
 * steven-joruk
 * davidlattimore
 * Nehliin
 * colelawrence
 * zmanian
 * alexkirsz
 * regiontog
 * berkus
 * belzael
 * vincentdephily
 * jam1garner
 * yvt
 * Shoeboxam
 * evanrichter
 * yerke
 * bes
 * seanpianka
 * srijs
 * kkysen
 * messense
 * riking
 * rafaelcaricio
 * Lemmih
 * memoryruins
 * pthariensflame
 * senden9
 * robjtede
 * Jonas Platte
 * zebp
 * spike grobstein
 * Oliver Marshall
 * Sam Harrington
 * Jonas
 * Jeff Muizelaar
 * Eugene Bulkin
 * Absolucy
 * Chris Butler
 * sierrafiveseven
 * Joseph Garvin
 * MarcoFalke
 * icewind
 * Tommy Thorn
 * Sebastian Zivota
 * Oskar Nehlin
 * Nicolas Barbier
 * Daniel
 * Thomas Colliers
 * Justin Ossevoort
 * sbstp
 * Chris
 * Bálint Horváth
 * fanquake
 * sstadick
 * luizirber
 * kiyoshigawa
 * robinmoussu
 * Daniel Sheehan
 * Marvin Löbel
 * nacaclanga
 * Matthew Conolly

and a few others who preferred to stay anonymous.

Former sponsors/patreons:

 * igrr
 * finfet
 * Alovchin91
 * wezm
 * stuhood
 * mexus
 * raymanfx
 * 0xdeafbeef
 * ghost
 * gilescope
 * Hofer-Julian
 * olanod
 * Denis Zaletaev
 * Chai T. Rex
 * Paul Ellenbogen
 * Dakota Brink
 * Botlabs
 * Cass
 * Oliver Marshall
