= rustc_codegen_gcc: Progress Report #21
:page-navtitle: rustc_codegen_gcc: Progress Report #21
:page-liquid:

== What is rustc_codegen_gcc?

https://github.com/rust-lang/rustc_codegen_gcc[rustc_codegen_gcc] is a
GCC https://en.wikipedia.org/wiki/Ahead-of-time_compilation[ahead-of-time] codegen for rustc, meaning that it
can be loaded by the existing rustc frontend, but benefits from GCC by having more architectures
supported and having access to GCC's optimizations.
It is not to be confused with gccrs, which is a GCC frontend for Rust.

== GCC patches status

This month, the following patch was reviewed and merged:

 * https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=6b432c0f777ab9b8436fb07f71de6ea4d259b869[jit, testsuite: fix a failing test by updating its error string [PR107999\]] (thanks to GuillaumeGomez!)

== State of rustc_codegen_gcc

Here's what has been done this month:

 * https://github.com/rust-lang/rustc_codegen_gcc/pull/254[Feature/simd scatter gather]
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/255[Sync from rust 2023/feb/28]
 * https://github.com/rust-lang/rustc_codegen_gcc/pull/256[Regen intrinsics] (thanks to GuillaumeGomez!)

My goal for this month was to finish implementing SIMD (at least for x86-64) and this is now done!
That was my first goal as https://foundation.rust-lang.org/news/community-grants-program-awards-announcement-introducing-our-latest-project-grantees/#introducing-our-newest-project-grantees[a project grantee of the Rust Foundation] (thanks to them for sponsoring me!).

There will be more work to do for SIMD in the future, in addition to adding the support for other architectures, e.g. producing more optimal code. Indeed, some intrinsics are currently implemented without SIMD, or only partly using SIMD, and others that didn't have a direct equivalent in GCC might not be optimal.

Here's a rough summary of what has been implemented:

[cols="<,<,1,1"]
|===
| Feature | Last month completion | Completion | Delta

| SIMD (x86-64).
| 95%
| 100%
| +5%

| Unwinding.
| 80%
| 80%
|

| LTO.
| 0%
|
|

| Debug info.
| 0%
|
|

| Endianness support for non-native 128-bit integers.
| 0%
|
|

| Rustup distribution.
| 0%
|
|

| SIMD for other architectures than x86-64.
| 0%
|
|

| Support for new architectures in libraries (libc, object, …) and rustc.
| 0%
|
|

| More function and variable attributes.
| 0%
|
|

| Target features (to detect what is supported in an architecture, like SIMD).
| 0%
|
|

| Basic and aggregate types.
| Done
|
|

| Operations, local and global variables, constants, functions, basic blocks.
| Done
|
|

| Atomics.
| Done
|
|

| Thread-local storage.
| Done
|
|

| Inline assembly.
| Done
|
|

| Many intrinsics.
| Done
|
|

| Metadata.
| Done
|
|

| Setting optimization level.
| Done
|
|

| Packed structures.
| Done
|
|

| Alignment, symbol visibility, attributes.
| Done
|
|

| 128-bit integers.
| Done
|
|
|===

// TODO: add progress of compiling some projects.

=== UI tests progress

Here are the results of running the UI tests in the CI:

 * https://github.com/rust-lang/rustc_codegen_gcc/actions/runs/4333731125/jobs/7567103865#step:19:2037
 * https://github.com/rust-lang/rustc_codegen_gcc/actions/runs/4333731125/jobs/7567103913#step:19:2017
 * https://github.com/rust-lang/rustc_codegen_gcc/actions/runs/4333731125/jobs/7567103942 (failures)

|===
| Category | Last Month | This Month | Delta

| Passed | 4821 | 5126 | +305
| Failed | 65 | 66 | +1
|===

There are many new tests since I synced with rustc, which hasn't been done since August.

For the next month, I'll continue investigating the issues with unwinding in release mode.

== How to contribute

=== `rustc_codegen_gcc`

If you want to help on the project itself, please do the following:

 1. Run the tests locally.
 2. Choose a test that fails.
 3. Investigate why it fails.
 4. Fix the problem.

Even if you can't fix the problem, your investigation could help, so
if you enjoy staring at assembly code, have fun!

=== Crates and rustc

If you would like to contribute on adding support for Rust on
currently unsupported platforms, you can help by adding the support
for those platforms in some crates like `libc` and `object` and also
in the rust compiler itself.

=== Test this project

Otherwise, you can test this project on new platforms and also compare
the assembly with LLVM to see if some optimization is missing.

=== Good first issue

Finally, another good way to help is to look at https://github.com/rust-lang/rustc_codegen_gcc/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[good first issues]. Those are issues that should be easier to start with.

== Thanks for your support!

I wanted to personally thank all the people that sponsor this project:
your support is very much appreciated.

A special thanks to the following sponsors:

 * saethlin
 * embark-studios
 * Traverse-Research
 * Shnatsel
 * Rust Foundation

A big thank you to bjorn3 for his help, contributions and reviews.
And a big thank you to lqd and https://github.com/GuillaumeGomez[GuillaumeGomez] for answering my
questions about rustc's internals.
Another big thank you to Commeownist for his contributions.

Also, a big thank you to the rest of my sponsors:

 * kpp
 * 0x7CFE
 * repi
 * nevi-me
 * oleid
 * acshi
 * joshtriplett
 * djc
 * TimNN
 * sdroege
 * pcn
 * alanfalloon
 * steven-joruk
 * davidlattimore
 * Nehliin
 * colelawrence
 * zmanian
 * alexkirsz
 * berkus
 * belzael
 * jam1garner
 * yvt
 * Shoeboxam
 * evanrichter
 * yerke
 * bes
 * seanpianka
 * srijs
 * kkysen
 * riking
 * Lemmih
 * memoryruins
 * senden9
 * robjtede
 * Jonas Platte
 * spike grobstein
 * Oliver Marshall
 * Sam Harrington
 * Jonas
 * Jeff Muizelaar
 * Eugene Bulkin
 * Chris Butler
 * sierrafiveseven
 * Joseph Garvin
 * MarcoFalke
 * athre0z
 * icewind
 * Tommy Thorn
 * Sebastian Zivota
 * Oskar Nehlin
 * Nicolas Barbier
 * Daniel
 * Thomas Colliers
 * Justin Ossevoort
 * sbstp
 * Chris
 * Bálint Horváth
 * fanquake
 * kiyoshigawa
 * robinmoussu
 * Daniel Sheehan
 * Marvin Löbel
 * nacaclanga
 * Matthew Conolly
 * 0x0177b11f
 * L.apz
 * JockeTF
 * davidcornu
 * stuhood
 * Myrik Lord
 * Mauve
 * icewind1991
 * T
 * nicholasbishop
 * Emily A. Bellows
 * David Vasak
 * Eric Driggers
 * Olaf Leidinger
 * UtherII
 * simonlindholm
 * lemmih

and a few others who preferred to stay anonymous.

Former sponsors/patreons:

 * igrr
 * finfet
 * Alovchin91
 * wezm
 * mexus
 * raymanfx
 * ghost
 * gilescope
 * olanod
 * Denis Zaletaev
 * Chai T. Rex
 * Paul Ellenbogen
 * Dakota Brink
 * Botlabs
 * Cass
 * Oliver Marshall
 * pthariensflame
 * tedbyron
 * sstadick
 * Absolucy
 * rafaelcaricio
 * dandxy89
 * luizirber
 * regiontog
 * vincentdephily
 * zebp
 * Hofer-Julian
 * messense
 * 0xdeafbeef
